---
title: Striving Towards Gender Inclusivity in STEM in India
author: 
    - Aarathi Parameswaran
date: 3-24-2021
---
*This is an op-ed piece I wrote for my undergraduate journalism course called Writing for the Media in 2021, on gender inclusivity in STEM in India.*

It is no revelation that Andrea Ghez, the winner of the 2020 Nobel prize in Physics, is only the fourth woman to achieve the feat in the 120-odd years it has been around. But while the fact comes as no surprise, it brings about a sense of uneasiness - there’s something terribly discomforting about it. While these prizes aren’t the best representation of scientific contribution to the field, they do a decent job in reflecting the biases that exist in the field - like when Rosalind Franklin was essentially robbed of due credit for the Nobel prize that was awarded to Watson and Crick for their model of DNA despite her significant contributions to the study. Gender discrimination is ingrained in science, as is in the rest of our culture.

According to the Global Gender Gap report, India is ranked 112th out of 149 countries. And the STEM field in the country remains no exception to these biases. In India, 40 percent of the STEM graduates are women but they comprise only 14 percent of the workforce. Women hold fewer senior positions of authority, are paid less than their male counterparts, and are severely underrepresented. And instances of discrimination, blatant or subtle, can be seen within the bounds of institutions; in the interactions in classrooms, the way certain faculty members are perceived, and how they are forced to have to assert their authority to be heard.

Within the STEM field as well, the gender ratios are severely skewed, owing to the supposed difference between what falls under ‘soft’ sciences and ‘hard’ sciences. For instance, biological or psychological sciences are deemed ‘soft’ sciences and tend to be female-dominated, while physics and engineering are considered ‘real’ or 'hard' sciences and are male-dominated. A possible explanation for this comes from the stereotype of women performing roles of caregiving or nurturing that are supposedly reflected in these so-called soft sciences and this work is considered easier than something more hands-on like those under the category of hard science.


The number of women at higher levels in the field progressively diminishes, particularly after the graduate levels - known as the ‘leaky pipeline’ effect, where the field is visualised as a series of pipes, with each higher level forming a new connecting pipe and women tend to ‘leak’ out of the pipe at higher stages. This happens because as women enter their mid-twenties, the pressure of getting married is inflicted upon them and they are forced to choose between taking care of and nurturing their family or working towards their career. The dearth of facilities and measures to provide women the means to pursue both simultaneously forces them to make this unreasonable choice.

Trans, non-binary, and gender non-conforming people have it much worse off in STEM, as they do in other walks of life since almost all dialogue on inclusivity in the field is limited to cisgender women. They face hostile work environments and are subject to harassment and exclusion. A study conducted by Science Mag in January 2021 shows that LGBTQ people in STEM are 30% more likely to face workplace harassment than their non-LGBTQ peers. One in two transgender physicists are harassed at university and research settings, according to a study by the American Physical Society. 
Anasuith P. Pridhvish, a trans woman who studies at a private university in Bangalore, tells Sayantan Datta in an article for the Life of Science, how the elevators are marked for ‘gents’ or ‘ladies’. She does not feel comfortable taking the elevator for males and does not have the option to use the one for females, which forces her to take eight flights of stairs every day. In India where recognition of these identities outside the binary of male and female seems like a far-fetched reality, the prevalence of gender-segregated spaces worsens their daily struggles and affects their mental health severely.

The UK has a framework that attempts to combat the issue. Called the Athena Scientific Women's Academic Network (SWAN) charter, it was established in 2005 and functions in different institutions and pushes them to address these issues related to gender by following the
charter's ten principles. Institutions registered with the charter are expected to achieve the prescribed gender equality objectives and meet equality legislation requirements. The network promotes inclusive working practices in institutions, which increases the retention of valued academics and helps build the reputation of the institution. The charter has also expanded to provide support to trans staff and students and men, wherever appropriate. According to reports, this model has been successful in the UK and has been implemented in Australia as well, called Science Australia Gender Equity (SAGE).

India's Department of Science and Technology (DST), as well as the US and Canada, are in the process of implementing a scheme based on Athena under the name of GATI - Gender Advancement through Transforming Institutions. They plan to get institutes to conduct self-assessments on gender equity and carry out initiatives like gender sensitization programs. The DST will have to work through a lot of bureaucracy, especially in the top institutions like IITs and NITS that are government-run. Moreover, these policies are mainly directed at cis women and are vague about trans people.

Gender sensitization programs for all members of an institute, as mentioned in GATI's plan of action, are a necessary step to create awareness of the discrimination that occurs and this paves the way to prevention of it by starting conversation about the topic. Affirmative action in the form of reservations, fee concessions and other measures for the upliftment of these marginalised and less privileged groups should also be ensured. Reservations are required for representation especially for positions of authority, which helps get rid of the negative stereotyping and makes room for more diverse role models in the field. It also becomes important to look at these measures through an intersectionality lens, keeping in mind the prevalence of caste and class barriers.
Providing gender-neutral spaces, the usage of the right pronouns, and gender affirmative policies are small steps that go a long way in creating a comfortable atmosphere for trans, non-binary, and gender non-conforming persons. Ensuring gender inclusivity is a daunting task, but not an impossible one. 