# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Aarathi Parameswaran"                                # Your name
  description: "Graduate student interested in networks and complexity"   # A brief slogan (optional)
  image: img/my_image.jpg
  

  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
 
    
    # your sub-pages
    left:
      - text: "About"
        href: about/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects & Courses"
        href: pandc/index.qmd
      - text: "Miscellaneous"
        href: misc.qmd


    
    # your social media handles
    right:
      - icon: twitter
        href: https://x.com/rtparam
      - icon: linkedin
        href: https://www.linkedin.com/in/aarathip
      - icon: github
        href: https://github.com/rtparam
      - icon: envelope
        aria-label: email
        href:  "mailto:aarathiparameswaran@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Aarathi Parameswaran</span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - darkly
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true