---
title: Wildlife in India
--- 
*Some of my work from the course 'Wildlife in India' in the sixth semester of my undergraduate degree at Azim Premji University*
---


The people of India have had a deep-rooted, fluctuating relationship with nature. Based on the discussions in class and the various texts provided to us, it is evident that this relationship today has evolved from one of reverence to one that sees nature as merely a repository of resources owing to events in the past and discourse on conservation has been and is limited to a small set of people in positions of privilege.

India’s relationship with nature stems from ancient history, seen from the Harappan civilisation. The hunter-gatherer tribes in the Indus valley civilisation had animals and plants involved in their lives, for which archaeological evidence exists in the form of seals that are found with animals like elephants, tigers, buffalos and rhinos and other art that depicts faunal diversity. Even in their spirituality – Harappan Gods were associated with plants and animals, adorned with horns and headgear made of plants, which symbolises the central role of nature in their lives. Different regions of the country also have several linguistic terms and superstitions regarding nature – like different names of the rain in Assam, myths of frogs being married, demons guarding the Kanchenjunga and other traditions. Forms of art and folklore also serve as sources of knowledge and should be acknowledged that way and not be taken for granted.

Throughout history, the people of India had a dependence on forests in the past, in particular a relationship of reverence. But this began to change with monarchy and colonialism. Kings from as early as the fifteenth century conducted wildlife hunts. The British also had significant cultural differences with respect to interactions with the environment, primarily with an economic incentive and for sport.

In accordance with this incentive, they found that getting rid of animals made it easier to control forests and expand agriculture. And as agriculture, land use and the population expanded, levels of conflict between people and animals also increased which led to a shift in people’s views. Animals were seen as vermin, and this was constantly reinforced by calling animals ‘pests. This gave a moral justification their extermination and highlights the importance of the language they used to describe animals. For example, they called the tiger a ‘cunning, silent, savage enemy’.
This impact of the usage of words and framing of nature constantly affected relationships with nature, even in the future and today. It gives the exploitation a different meaning as forests today are seen as ‘inert objects’ that are used as repositories of resources. This justification of looting nature stemmed from the past and has percolated to the present day.

Wildlife laws today have been heavily influenced by the colonisers. Gadgil and Guha describe in their book ‘Conquest and Control’ the link between imperialism and environmental degradation. World ecology has been profoundly altered by western capitalism, colonialism and global control of resources. The British used India’s forests extensively for coal, timber for industrial and political needs. Most
significant was the use of teak for shipbuilding and the railways in the 1800s. 

The British saw railways as a necessity, not for the movement of people (which was one reason the people saw it as a useful contribution to their lives) but for the faster movement of goods to ports. The extensive network of railways in the country led to severe deforestation. Trees were felled for creating the tracks, clearing area and for coal. The only kinds of timber that could be used were teak, Sal and Deodar and at the time of railway expansion, Indian forests looked inexhaustible.
Eventually, in 1862, they realised that this wasn’t true and the forest department made forest conservancy of administrative importance to “ensure the sustained availability of forests to meet the enormous requirements of the railways”. The existing system in place was based on community norms so new rules were brought in that attempted to bring large parts of the forest under state control. The three contesting views were of annexing all forests and bring under state control, a more liberal view which was to respect the existing community norms – letting some parts remain common and a pragmatic view to bring forests under state control along with negotiating with the locals.
It was in this context that the Indian Forest Act was brought about in 1865 to assert state monopoly through it. It facilitated the acquisition of those forest areas designated for railway use. It was ensured that existing rights did not overrule the state from accessing it. It was hastily done and had a lot of loopholes. This required a memorandum in 1875 which led to the Indian Forest Act of 1878. While the 1878 act still brought forests under state control, it sought that state intervention be minimal, respecting existing norms.

While this was the time of the inception of a growing consciousness amongst political actors about the environment and its resources (which may or may not have been an implication of political agenda) that later extended to prominent figures like Indira Gandhi, Salim Ali, J C Kumarappa who were vocal about protecting the environment and brought about policy changes, there was still the debate of the dichotomy between development and sustainably and whether they could happen at the cost of the other. While these figures played important roles in conservation, them being the forerunners can be unsettling because they are not the people directly impacted by the effects of environmental degradation and possibly why they should not be taken at face value, as seen from the incident of the Bharatpur bird sanctuary. The marginalised communities that live in the forests and rely on them and vice versa should be the voices of
conservation and not be sidelined as is the case today.


