---
title: On Prison Abolition
author:
    - Aarathi Parameswaran
---
*This is an essay I wrote for my undergraduate course on Public Reasoning in 2020.*

---

The Prison Industrial Complex should be abolished. 

The idea of locking people up as a form of punishment has existed since the time of monarchy. But so has the idea of corporal punishment and its other brutal forms- for instance, burning people alive for petty treason under the English common law. If the latter has been abolished, there is no reason why the former shouldn't be. And the justification for abolition follows. 

The problem with prisons is that it is morally wrong to lock people up and put them away from society, as their lives are not given any value as human beings anymore.  It causes the breaking up of families, cultural degradation, and destruction of livelihoods and it further exacerbates societal harms instead of fixing them. Incarceration hasn't been proven successful, as there has been no decrease in crime rates or an increase in public safety. The prison population in the world has seen about a 500% increase in the past four decades, but there has only been an increase in crime rates, going from a 13% increase in 1980 to a 45% increase in 2019. In America, there are four and a half times as many crimes in every million population today as there were twenty years ago. 
The recidivism rates have also been growing - with an average follow-up period of two years in a study conducted for 11 countries, reported re-arrest rates were between 26% and 60%, reconviction rates ranged from 20% to 63%, and reimprisonment rates varied from 14 to 45%.
The other inherent problem with the idea of the prison system is the treatment of inmates in penitentiaries. They are not given any means to better their life outside of prisons. It does not give means to provide adequate housing, access to education or living wage jobs, or even proper mental health treatment. Many individuals released from prison have difficulty finding jobs to support themselves and reconnecting with family members. The activist and researcher James Kilgore, himself formerly incarcerated, has said, “The overwhelming problem for people inside prison is not that their labor is super exploited; it’s that they’re being warehoused with very little to do and not being given any kind of programs or resources that enable them to succeed once they do get out of prison.”  Imprisonment destroys employment prospects and family ties, contributing to persistent poverty, inequality and intergenerational cycles of disadvantage. This also emphasises the need to remove the stigma associated with former convicts. 

It also propagates forms of slavery and enhances the existing social hierarchies, resulting in ill-treatment of the already vulnerable groups, like women, transgenders, lower castes, etc. There is also a clear racial disproportion in the prison populations across the world. Angela Davis, a renowned abolitionist, has said in her book ‘Are Prisons Obsolete? (2003)’,“Are we willing to relegate ever larger numbers of people from racially oppressed communities to an isolated existence marked by authoritarian regimes, violence, disease, and technologies of seclusion that produce severe mental instability?”
Moreover, a majority of people incarcerated are because of petty, non-harmful crimes that do not require confinement, like drug abuse, possession, vagrancy, etc. For instance, in Texas, 524,000 people were jailed in 2018 for unpaid traffic tickets. Other problems that have led to mass incarceration is the unnecessary criminalization of certain unavoidable factors, like poverty, vagrancy, drug abuse and addiction, which are either caused due to mental illnesses or are beyond the reach of those in the lower strata of society, for which they do not receive treatment for in prisons.

Prisons in India are also notorious for their poor living conditions. With an average occupancy rate of 115% of their capacity, Indian jails continue to remain congested and overcrowded, numbers in the National Crime Records Bureau’s “Prison Statistics India – 2017” report has revealed. 

The amount of money invested in prisons does not reap the benefits it claims to. In the US, more money is being spent on prisons than education. Around 15 states spend at least $27,000 more per prisoner than they do per student. This futile act of incarceration costs a lot of money, which can rather be invested in more fruitful activities like healthcare or education, which will help alleviate the problems in society.
 
People commit crimes either due to the poor conditions they are forced to live in, mental health issues or out of ill will. And the reasons for their incarceration are firstly, to bring about reform and rehabilitation to those who have been convicted, and secondly, the retributive reasons for those who do it out of harmful tendencies. The first reason has been proven ineffective, as seen from the statistics of crime rates and recidivism. Addressing the reason for retribution, a paper by Andrew Oldenquist in the Journal of Philosophy (1988) gives insight into retribution, offering both sides of the argument. Though he claims that morally accepting retribution is vital to a viable moral community, it can empirically become revenge. And he also says that the fact that retribution has utility does not give us reason to accept it.
“If we say retribution has utility, we could mean that we have a better society if people falsely believe members of their moral community sometimes deserve to be punished. This is the "noble lie" view. It is, I believe, elitist in the bad sense; the very idea of philosophy seems absurd if philosophers must conclude that the best world is one in which the majority of people must believe what is false.” 
Martha C Nussbaum, a professor of law and ethics at the University of Chicago says on the inefficacy of retribution, “It is very natural to resent when one is wronged, and the demand for payback or retribution, which is in my view the most problematic aspect of anger, probably has an evolutionary basis. Punishment of some type may be useful for the future, by deterring wrongdoing and reforming offenders. But the retributive idea of blood for blood is useless and hollow: killing doesn’t bring back the dead, it just creates a chain of resentment that is bad for individuals and bad for society.” 

It is thus evident that the idea of prisons is hypocritical as it violates human rights in order to correct/punish those who violate human rights. This brings about the need for an alternative, which can be seen from examples of countries who have succeeded in their methods of ‘prison’. The most effective prisons are the ones that look least like prisons.
 For instance, Scandinavian countries like Norway have paved the way for such systems. Their focus is on rehabilitation and not retribution. There are no bars, barbed wires or cells. The underlying principle is restorative and transformative justice.
 Restorative justice involves those convicted engaging in dialogue with the individual and communities affected by their actions. They must then work with those parties to develop actions to try to repair the damage done as much as possible. The process is restorative because the goal is to restore the victim, their community, and the offender, to how they were before the transgression occurred. People who commit violence are hurt by the violence they commit and therefore need to be part of any process that seeks to find justice for that violence. Transformative justice is the concept of asking the offender what in their life has led them to commit the act, and what we all can do to change those conditions. Through either restorative or transformative justice, the systemic analysis takes the place of individual interrogation and punishment. It may be hard to imagine a victim of a violent transgression sitting down for a discussion with the perpetrator, but there have been many situations in which the victim or the victim’s family has actually been more fulfilled by a restorative process, or feel they have attained greater justice through restorative-justice models. An obvious benefit of the restorative model is that it takes into account not just the singular event, but the structural problems surrounding and leading up to the offence. 
These methods have been successful because they incorporate the fact that people change and as Aristotle said, can practice to become more virtuous. This is also reflected in the statistics of these nations. In Norway, only one in five (20%) of adults leaving prison are reconvicted within two years of release. Similar reoffending rates are seen across the Scandinavian nations. In Uruguay’s National Rehabilitation Centre, the recidivism rate is just 12%; in Germany, it’s 33% within three years. Norway's incarceration rate is just 75 per 100,000 people, while in the US it is 707. The crime rates are also among the lowest. 

People deserve a second chance because many grow and change. They robbed to feed an addiction and then got sober. They assaulted someone because they were mentally ill and then got treatment and stabilized. They mature as they age beyond their teens and early 20s. That’s why we need to treat them as humans and abolish prisons. 













