---
title: How Skateboarding Keeps Kids in School in Kerala
author:
    - Aarathi Parameswaran
date: 3-17-2021
---

*This is a feature story I wrote for my undergraduate journalism course called Writing for the Media. It is a piece about a skateboarding group in my hometown and an NGO-run school in my state that helps get children off the streets with skateboarding as an incentive. I wrote this in 2021, after interviweing all the people mentioned in the piece, and since then the group have successfully built the first skate park in the city.*

---

Outside the Jawaharlal Nehru Stadium in Kochi, a five-year-old skateboarder, Janaki Anand - clad in a little purple polka dot frock, safety pads, and a helmet almost double the size of her head - successfully landed a skateboarding stair shredding trick after numerous attempts, and brought her to tears of joy. Her video went viral and moved many on Instagram,
generating about 3.3 million views. This scene is just a glimpse into the fiery passion for skateboarding in Kerala, where the sport has not only been getting people on skateboards and onto the streets but is also getting kids off the streets and into schools.

The sport found its origins in the 1940s, starting as ‘sidewalk surfing’ and since then it has grown to be one of the most popular sports in the world. The upcoming Tokyo Olympics is also set to witness the sports official entry into the Olympics. Skateboarding is still relatively new in India, with the first skate park having opened only in 2003 in Goa. Nevertheless, the last decade has seen a significant surge in skateboarders from India, who have also gained worldwide
recognition.

Like the rest of the country, Kerala was also quick to catch up on the skateboarding scene. FlySquad is Kochi’s first and only registered skateboarding club. It was started by a group of seven people who began skateboarding after seeing it in action for the first time in the sports store, Decathlon. It was officially registered in December 2015, but its popularity grew after the success of its Instagram handle, created in 2017. Joel Abhishek, one of the founding members of FlySquad says “Our mission is to create a skateboarding community in the city, where we can share skateboarding knowledge and help people get into the sport, training them with the basics for no fee. That’s why we have no joining fee - we’re open to all”. Members of the club meet every evening between 7 PM and 12 AM outside the Jawaharlal Nehru Stadium to practice together, learn new tricks and conduct other activities like street dancing, hip-hop, and rapping. The group also organises events and workshops in schools and cafes. Every year on June 21st, which is the international day of skateboarding, boarders from across the city meet to celebrate together. In 2020, given the pandemic, conducting an event of this sort was off-limits. Instead, they skateboarded all over the city and delivered food packets to the homeless.

Skating on roads often gets these boarders into trouble with the police. On the 27th of October 2020, a couple of boarders were stopped by the police, who seized their skateboards for no apparent reason, even though they followed all COVID protocol. The scene drew a crowd and a video about the incident that was circulated on social media went viral which gave FlySquad gained immense support from the public.

Sreekumar Santhosh, popularly known as Sreekuttan says, “the biggest problem is that Kochi does not have a skate park. If there was a skate park, we wouldn’t have to get on the streets and get into trouble with the cops. People from other districts like Kasaragod and Thrissur come here to skate, so given the number of skaters, we definitely need a park. We also need one if we want to compete professionally - flat ground and roads are not enough for practice, we need to get used to ramps”.
A few boarders from FlySquad attended a national competition called Jugaad in December 2019. They participated but could not win because they did not have enough practice within a skate park. “We need to regularly practice with ramps if we want to compete. There are only two skate parks in Kerala- in Calicut and Kovalam, and going there means travelling for 400 kilometres, which is not easy”, says Sreekuttan.
Land for the skate park in Kochi has been made available, a company has agreed to do the construction free of cost and Decathlon has also guaranteed support. The only problem they face now is the lack of funds for the material since government authorities are not willing to sponsor the park. Sreekuttan mentions, “ Professionally, I’m a graphic designer but skateboarding is my passion. The plan is that in a few years when the skate park is ready, we’re going to turn FlySquad into a brand and set up a skate shop to make and sell boards, spare parts, t-shirts, and other merchandise”.

Further south in the state, in the beach town of Kovalam, skateboarding is more than just a sport. It is a second chance at education for some kids, owing to an NGO called Sebastian Indian Social Projects (SISP) launched by a social work graduate from Belgium, Paul Van Gelder in 1996. They aim to help students who have dropped out of school to complete their education, using skateboarding as an incentive. The school has two main policies: ‘no school, no skateboarding’ and ‘girls first’. Initially, a surf club was created and surfing was used as the incentive, but this led to a lot of problems - some kids were scared of the sea or allergic to the polluted seawater, and girls weren’t allowed to surf as the fishermen community in the area believed that girls shouldn’t go near the beach, especially in their adolescent years. Moreover, they could only surf from October to May, given the conditions of the sea. Thus surfing as an incentive to attend school did not succeed, although the surf club is renowned and is a source of employment for many people in the region.
Yet, skateboarding served as an ideal replacement. A former student at the SISP school and the current coach, Vineeth Vijayan was given a skateboard from a friend, taught himself through YouTube, and realised that this would be more appealing than surfing, apart from being more convenient. A skate park and a mini ramp were built in the school in 2013, and around thirty students attended initially. Only if students attended school through the week were they allowed to skate on the weekends. This is easy to keep track of since the two skate parks are within the school compound and on the terrace. The SISP school provides basic education, following the regulations as prescribed by the government, also extending special provisions for students over the usual age group and free meals and insurance to the children as well as their families.
Educational care beyond the school level is also provided, with students earning bachelor’s degrees as well. “Some of these kids were having a tough time before on the streets, dealing with problems of smoking, alcohol and drugs. Skateboarding has been a turning point in many of their (students) lives, including mine. It completely changed their lifestyle”, says coach Vineeth. The families of these students are skeptical about skateboarding, claiming that it’s of no use as it won’t bring in a steady income. “Once they pass their tenth grade exams, families are reluctant to continue sending them as they believe the tenth certificate is enough to get them a job”, says Vineeth. “After students won national level competitions and received certificates, it got a lot better as they realised that it was about talent, which they have, and not just money”. At the national competition held in Vizag in 2019, their students won four gold and two silver medals. Vidya Das, a seventh grade student and national level winner says, “I’ve gotten opportunities I would not have otherwise. I got to travel across the country, act in advertisements and movies”. She travelled to Rajasthan last year to shoot for an upcoming Netflix movie on skateboarding called Skater Girl. Joshan J, a tenth grade student at SISP mentions, “I heard about this place
through my friend. If it wasn’t for skateboarding, I wouldn’t go to school”. One of the gold medallists at Vizag, he aspires to become a professional skateboarder. Students winning at these levels give parents some confidence, but it isn’t always affirmative. The school faces the problem of getting the parents to trust them.
The issue of reluctance from parents is further exacerbated in the case of girls. “The fishermen community in the area is very traditional. By the time girls turn sixteen, they are not allowed to take part in sports as they believe this is when they have to learn how to become good wives and mothers”, says founder Paul Van Gelder. To combat this issue, in addition to the ‘girls first’ rule
they have a female coach and girls-only sessions, to make the parents feel more comfortable. In spite of this, only 25% percent of the skaters are girls. This gender gap is also evident within FlySquad, which has less than ten female skaters. Sixteen-year-old Hadhiya Jannath, who goes by Kazi, is FlySquad’s youngest member. She says, “My parents are very supportive, but they are always taunted by other people in my society, especially when they see my older male skateboarder friends dropping me home late at night. They think I’m going down the wrong road. Only if this attitude changes will more girls be encouraged to join”.

Financial uncertainties are also a lingering problem for SISP. “Like most NGOs, we also have problems with getting sponsors and funding for materials. Skateboards and equipment are expensive and the kids need at least 3-4 pairs of shoes every year, as they wear out and get torn easily”, says Paul. Commenting on the effect of the pandemic he says, “The pandemic has been a problem as we had to stop our activities when the triple lockdown was enforced. We have two skateparks and only five children were allowed to use them at a time. Parents also did not allow their kids to come to school out of fear of the virus”. Vineeth mentions, “At the start of the pandemic, I went to their houses to give them masks, food and phones for them to attend classes online. If they had to recharge their internet, they called me and I did it for them. But it was difficult to get them to study”. 
The effect the pandemic had in getting the students to study brings up the question of how feasible incentive-based education of this sort is. Ramchandar Krishnamurthy, a professor of education at Azim Premji University whose research explores the philosophical and
socio-political perspectives on education, though skeptical about the use of incentives, agrees that these can be very useful in getting students to attend schools. He says, “If these extrinsic incentives for motivation are seen as a scaffolding, where students experience education and develop a taste for it, it is just a pragmatic choice and I see no problem with it”.

Skateboarding has been integrated into Kerala’s sport culture, be it an incentive to education or just a hobby, and the passion people have for it is remarkable. Sreekuttan says, “People always ask us why we carry these wooden planks every day, what use does it have? We need to make them realize that the happiness we get out of it isn’t just to put on a show, it’s what gives us freedom”.